/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface;
import business.Account;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author gagan
 * 
 */
public class ViewAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAccountJPanel
     */
    
    private JPanel userProcessContainer;
    private Account account;
    
    ViewAccountJPanel(JPanel userProcessContainer,Account account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateAccountDetails();
        btnsave.setEnabled(false);
        btnback.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblroutingnumber = new javax.swing.JLabel();
        lblaccountnumber = new javax.swing.JLabel();
        lblbankname = new javax.swing.JLabel();
        txtroutingnumber = new javax.swing.JTextField();
        txtaccountnumber = new javax.swing.JTextField();
        txtbankname = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("View Account");

        lblroutingnumber.setText("Routing Number:");

        lblaccountnumber.setText("Account Number:");

        lblbankname.setText("Bank Name:");

        txtroutingnumber.setEnabled(false);

        txtaccountnumber.setEnabled(false);
        txtaccountnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccountnumberActionPerformed(evt);
            }
        });

        txtbankname.setEnabled(false);
        txtbankname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbanknameActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(255, 204, 153));
        btnback.setText("Back");
        btnback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(255, 204, 153));
        btnsave.setText("Save");
        btnsave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsave.setEnabled(false);
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 204, 153));
        btnupdate.setText("Update");
        btnupdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblaccountnumber)
                            .addComponent(lblroutingnumber)
                            .addComponent(lblbankname, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtroutingnumber)
                            .addComponent(txtaccountnumber)
                            .addComponent(txtbankname, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnback)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnback, btnsave, btnupdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltitle)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblroutingnumber)
                    .addComponent(txtroutingnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccountnumber)
                    .addComponent(txtaccountnumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbankname)
                    .addComponent(txtbankname))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnback))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnback, btnsave, btnupdate});

    }// </editor-fold>//GEN-END:initComponents

    private void txtaccountnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccountnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccountnumberActionPerformed

    private void txtbanknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbanknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbanknameActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String routingnumber=txtroutingnumber.getText();
        String accountnumber=txtaccountnumber.getText();
        String bankname=txtbankname.getText();
        if(routingnumber.equals("") || accountnumber.equals("") || bankname.equals(""))
        {JOptionPane.showMessageDialog(this, "Cannot update with empty text fields!");
        return;
        }
        account.setRoutingnumber(routingnumber);
        account.setAccountnumber(accountnumber);
        account.setBankname(bankname);
        
        btnsave.setEnabled(false);
        btnupdate.setEnabled(true);
        JOptionPane.showMessageDialog(this,"Account created successfully!");
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        txtroutingnumber.setEnabled(true);
        txtbankname.setEnabled(true);
        txtaccountnumber.setEnabled(true);
        btnsave.setEnabled(true);
        btnupdate.setEnabled(false);
        
    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel lblaccountnumber;
    private javax.swing.JLabel lblbankname;
    private javax.swing.JLabel lblroutingnumber;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField txtaccountnumber;
    private javax.swing.JTextField txtbankname;
    private javax.swing.JTextField txtroutingnumber;
    // End of variables declaration//GEN-END:variables

    private void populateAccountDetails() {
        txtaccountnumber.setText(account.getAccountnumber());
        txtroutingnumber.setText(account.getRoutingnumber());
        txtbankname.setText(account.getBankname());
    }
}
